---
layout: null
---
var index = new elasticlunr.Index;
index.setRef('lunr_id');
index.saveDocument(false);
index.addField('pid'); 
index.addField('_title'); 
index.addField('_date'); 
index.addField('_format'); 
index.addField('_name'); 
index.addField('_subjects'); 
index.addField('_summary'); 
index.addDoc({"lunr_id":0,"link":"{{ site.baseurl }}/photos/1/","pid":"1","_title":"Butler Library - Looking West","_date":"1934","_format":"photographs","_name":"Warman, Manny, -1983","_subjects":"Academic libraries; New York (N.Y.); Butler Library","_summary":"View of Butler Library through foliage and a fence, looking west, 1934."}); 
index.addDoc({"lunr_id":1,"link":"{{ site.baseurl }}/photos/10/","pid":"10","_title":"Butler Library Exterior Lamp","_date":"circa 1933-1934","_format":"photographs","_name":"Beals, A. Tennyson","_subjects":"Academic libraries; New York (N.Y.); Butler Library","_summary":"View of one of the light fixtures on the outside of Butler Library, ca. 1933-34."}); 
index.addDoc({"lunr_id":2,"link":"{{ site.baseurl }}/photos/100/","pid":"100","_title":"Columbia Bicentennial Display","_date":"between 1934 and 2009","_format":"photographs","_name":"Warman, Manny, -1983","_subjects":"Academic libraries; Women college students; New York (N.Y.)","_summary":"'Students discuss one of the panels in Columbia University's Bicentennial Exhibit entitled 'A Man's Right to Knowledge and the Free Use Thereof.' A funereal design surrounds a photograph showing the damaged front of the office of La Prensa, the opposition newspaper in Buenos Aires, Argentina, closed by order of Juan Peron, January 26, 1951. The quotation from John Locke reads: '...if what (a man) holds be, as he gives out, well fenced with evidence, and he sees it to be true, what need he fear to put it to the proof?...He whose assent goes beyond his evidence owes this excess of his adherence only to prejudice, and does, in effect, own it....declaring thereby that it is not evidence he seeks but the quiet enjoyment of the opinion he is fond of...''"}); 
index.addDoc({"lunr_id":3,"link":"{{ site.baseurl }}/photos/11/","pid":"11","_title":"Butler Library - Looking West","_date":"between 1934 and 2009","_format":"photographs","_name":"","_subjects":"Academic libraries; New York (N.Y.); Butler Library","_summary":"View of Butler Library through foliage, looking west."}); 
index.addDoc({"lunr_id":4,"link":"{{ site.baseurl }}/photos/12/","pid":"12","_title":"Consulting the Card Catalog","_date":"between 1934 and 2009","_format":"photographs","_name":"","_subjects":"Academic libraries; New York (N.Y.); Butler Library","_summary":"Image of patrons using the card catalog in Butler Library."}); 
index.addDoc({"lunr_id":5,"link":"{{ site.baseurl }}/photos/13/","pid":"13","_title":"College Reading Room","_date":"between 1934 and 2009","_format":"photographs","_name":"","_subjects":"Academic libraries; New York (N.Y.); Butler Library","_summary":"View of the college reading room (226 Butler Library)."}); 
index.addDoc({"lunr_id":6,"link":"{{ site.baseurl }}/photos/14/","pid":"14","_title":"Cataloging Room","_date":"between 1934 and 2009","_format":"photographs","_name":"Ballou, Hubbard W.","_subjects":"Academic libraries; Cataloging; New York (N.Y.); Butler Library","_summary":"Overhead view of the cataloging room."}); 
index.addDoc({"lunr_id":7,"link":"{{ site.baseurl }}/photos/15/","pid":"15","_title":"Columbia Encyclopedia Publication Party","_date":"between 1934 and 2009","_format":"photographs","_name":"Warman, Manny, -1983","_subjects":"Academic libraries; New York (N.Y.)","_summary":"Professor Tyndall and Dwight Miner at the publication party for the Columbia Encyclopedia."}); 
index.addDoc({"lunr_id":8,"link":"{{ site.baseurl }}/photos/16/","pid":"16","_title":"Browsing Room, December 1945","_date":"December, 1945","_format":"photographs","_name":"","_subjects":"Academic libraries; New York (N.Y.); Butler Library","_summary":"Students in the Butler Library Browsing Room, December 1945."}); 
index.addDoc({"lunr_id":9,"link":"{{ site.baseurl }}/photos/17/","pid":"17","_title":"Butler Library Construction 26","_date":"1-Jun-33","_format":"photographs","_name":"Beals, A. Tennyson","_subjects":"Academic libraries; New York (N.Y.); Butler Library","_summary":"Butler Library construction, 1 June 1933."}); 
index.addDoc({"lunr_id":10,"link":"{{ site.baseurl }}/photos/18/","pid":"18","_title":"Film Editing","_date":"circa 1947","_format":"photographs","_name":"","_subjects":"Academic libraries; New York (N.Y.)","_summary":"CMC (Columbia Movie Club?) members editing film, ca. 1947."}); 
index.addDoc({"lunr_id":11,"link":"{{ site.baseurl }}/photos/19/","pid":"19","_title":"Butler Library at Night","_date":"November, 1937","_format":"photographs","_name":"Janovsky, Seymour","_subjects":"Academic libraries; Butler Library; New York (N.Y.); Butler Library","_summary":"View of Butler Library at night as viewed from across 116th Street, November 1937."}); 
index.addDoc({"lunr_id":12,"link":"{{ site.baseurl }}/photos/2/","pid":"2","_title":"Butler Library Construction 29","_date":"7-Oct-33","_format":"photographs","_name":"Beals, A. Tennyson","_subjects":"Academic libraries; New York (N.Y.); Butler Library","_summary":"Butler Library construction, 7 October 1933."}); 
index.addDoc({"lunr_id":13,"link":"{{ site.baseurl }}/photos/20/","pid":"20","_title":"Butler Library Construction 20","_date":"20-Jan-33","_format":"photographs","_name":"Beals, A. Tennyson","_subjects":"Academic libraries; New York (N.Y.); Butler Library","_summary":"Butler Library construction, 20 January 1933."}); 
index.addDoc({"lunr_id":14,"link":"{{ site.baseurl }}/photos/21/","pid":"21","_title":"Book Transfer","_date":"31-Aug-34","_format":"photographs","_name":"Boldtman, J.","_subjects":"College campuses; New York (N.Y.)","_summary":"31 August 1934. Boxes of books loaded onto the book chute next to the Alma Mater on their way across campus. Between August 20 and September 19, 1934 student workers and professional movers moved books from their original home in Low Library to their new home in South Hall (Butler Library)."}); 
index.addDoc({"lunr_id":15,"link":"{{ site.baseurl }}/photos/22/","pid":"22","_title":"Butler Library at Dusk","_date":"between 1934 and 2009","_format":"photographs","_name":"Warman, Manny, -1983","_subjects":"Academic libraries; New York (N.Y.); Butler Library","_summary":"View of Butler Library at dusk from across 116th Street, looking south."}); 
index.addDoc({"lunr_id":16,"link":"{{ site.baseurl }}/photos/23/","pid":"23","_title":"Ceiling-Butler Library","_date":"circa 1934","_format":"photographs","_name":"Wurts Bros. (New York, N.Y.)","_subjects":"Academic libraries; Decoration and ornament; New York (N.Y.); Butler Library","_summary":"Detail view of the ceiling in the Butler Library of Philosophy located in South Hall (Butler Library), ca. 1934."}); 
index.addDoc({"lunr_id":17,"link":"{{ site.baseurl }}/photos/24/","pid":"24","_title":"Book Transfer","_date":"between August 20 and September 19, 1934","_format":"photographs","_name":"Sprague","_subjects":"College campuses; New York (N.Y.)","_summary":"Image of student workers moving boxes from book chutes onto book carts at the foot of stairs to Low Plaza. Between August 20 and September 19, 1934 student workers and professional movers moved books from their original home in Low Library to their new home in South Hall (Butler Library)."}); 
index.addDoc({"lunr_id":18,"link":"{{ site.baseurl }}/photos/25/","pid":"25","_title":"Browsing Room","_date":"between 1934 and 2009","_format":"photographs","_name":"Bubley, Esther","_subjects":"Academic libraries; College students; New York (N.Y.); Butler Library","_summary":"Students in Butler Library's Browsing Room."}); 
index.addDoc({"lunr_id":19,"link":"{{ site.baseurl }}/photos/26/","pid":"26","_title":"Butler Library Stacks","_date":"circa 1934-1939","_format":"photographs","_name":"","_subjects":"Academic libraries; New York (N.Y.); Butler Library","_summary":"Main transverse stack aisle showing continuous beam less ceiling and tile covered floor, ca. 1930s."}); 
index.addDoc({"lunr_id":20,"link":"{{ site.baseurl }}/photos/27/","pid":"27","_title":"Columbia' Gate","_date":"between 1934 and 2009","_format":"photographs","_name":"Bubley, Esther","_subjects":"Academic libraries; New York (N.Y.); Butler Library","_summary":"Students walking through 'Columbia' gate on the main level of Butler Library."}); 
index.addDoc({"lunr_id":21,"link":"{{ site.baseurl }}/photos/28/","pid":"28","_title":"Butler Library - Main entrance mural","_date":"between 1934 and 2009","_format":"photographs","_name":"Look magazine","_subjects":"Academic libraries; Mural painting and decoration; New York (N.Y.); Butler Library","_summary":"Man and woman on bench in front of the main entrance mural of Athene painted by Eugene Savage of the Yale School of Fine Arts. Attributed to Look Magazine"}); 
index.addDoc({"lunr_id":22,"link":"{{ site.baseurl }}/photos/29/","pid":"29","_title":"Butler Library Construction Pit","_date":"before 1931","_format":"photographs","_name":"Boldtman, J.","_subjects":"College campuses; Building; New York (N.Y.)","_summary":"View of the construction pit on the site of the future Butler Library."}); 
index.addDoc({"lunr_id":23,"link":"{{ site.baseurl }}/photos/3/","pid":"3","_title":"Book Returns to Columbia Library After 178 Years","_date":"6-Sep-50","_format":"photographs","_name":"Warman, Manny, -1983","_subjects":"Academic libraries; New York (N.Y.)","_summary":"Enos M. Johnson (left) of Brooklyn, hands rare volume over to Dr. Richard H. Logsdon, associate director of the Columbia University Libraries. The book, entitled 'A System of Natural Philosophy,' was drawn from the shelves of the old King's College library in 1772 -- a dozen years before King's College became Columbia. It was recently discovered by Mr. Johnston as he rummaged through the attic at the home of his aunt, Miss Susan Ruggles of Binghamton, N.Y. The scholar who borrowed the book was Robert Harpur, one-time librarian of King's College and tutor of Alexander Hamilton. It was not regarded as 'overdue' at the University library, which was fortunate in view of the fact that a considerable fine would have been in order. The fine, calculated at the rate of five cents per day, would have totaled $3,248.50. Dr. Logsdon expressed the Library's gratitude for the return of the volume. 'The Library is especially happy to have this historic volume come back into its possession,' said Dr. Logsdon. 'We are most grateful to Mr. Johnston. The book, spanning virtually all of Columbia's life through nearly two centuries of American history, will serves as an interesting item for exhibition in Columbia's coming Bicentennial celebration in 1954.' (from: press release attached to image)"}); 
index.addDoc({"lunr_id":24,"link":"{{ site.baseurl }}/photos/30/","pid":"30","_title":"Butler Library Construction 4","_date":"15-Jun-32","_format":"photographs","_name":"Beals, A. Tennyson","_subjects":"Academic libraries; New York (N.Y.); Butler Library","_summary":"Butler Library construction, 15 June 1932."}); 
index.addDoc({"lunr_id":25,"link":"{{ site.baseurl }}/photos/31/","pid":"31","_title":"Columbia University, New York","_date":"1902","_format":"postcards","_name":"","_subjects":"Columbia University","_summary":""}); 
index.addDoc({"lunr_id":26,"link":"{{ site.baseurl }}/photos/32/","pid":"32","_title":"Exhibit of French Universities at Butler Library","_date":"1954","_format":"photographs","_name":"","_subjects":"Academic libraries; New York (N.Y.); Butler Library","_summary":"Image of (L to R) Pierre Douzelot, President Grayson Kirk, Jean Sarrailk, and Henri Bonnet examining a part of the exhibit of French Universities at Butler Library, 18 October 1954."}); 
index.addDoc({"lunr_id":27,"link":"{{ site.baseurl }}/photos/33/","pid":"33","_title":"Butler Library Construction 12","_date":"7-Sep-32","_format":"photographs","_name":"Beals, A. Tennyson","_subjects":"Academic libraries; New York (N.Y.); Butler Library","_summary":"Butler Library construction, 7 September 1932."}); 
index.addDoc({"lunr_id":28,"link":"{{ site.baseurl }}/photos/34/","pid":"34","_title":"Book Sorting Shelves","_date":"between 1934 and 2009","_format":"photographs","_name":"","_subjects":"Academic libraries; New York (N.Y.)","_summary":"Books on book sorting shelves with sloping backs and bottoms."}); 
index.addDoc({"lunr_id":29,"link":"{{ site.baseurl }}/photos/35/","pid":"35","_title":"College Library Reading Room","_date":"between 1934 and 2009","_format":"photographs","_name":"Warman, Manny, -1983","_subjects":"Academic libraries; Reading rooms; New York (N.Y.); Butler Library","_summary":"College students studying in the reading room."}); 
index.addDoc({"lunr_id":30,"link":"{{ site.baseurl }}/photos/36/","pid":"36","_title":"Butler Library Construction 28","_date":"25-Oct-33","_format":"photographs","_name":"Beals, A. Tennyson","_subjects":"Academic libraries; New York (N.Y.); Butler Library","_summary":"Butler Library construction, 25 October 1933."}); 
index.addDoc({"lunr_id":31,"link":"{{ site.baseurl }}/photos/37/","pid":"37","_title":"Butler Library Front Door","_date":"between 1934 and 2009","_format":"photographs","_name":"Beals, A. Tennyson","_subjects":"Academic libraries; New York (N.Y.); Butler Library","_summary":"View of Butler Library's main entrance."}); 
index.addDoc({"lunr_id":32,"link":"{{ site.baseurl }}/photos/38/","pid":"38","_title":"Butler Library Construction 14","_date":"3-Oct-32","_format":"photographs","_name":"Beals, A. Tennyson","_subjects":"Academic libraries; New York (N.Y.); Butler Library","_summary":"Butler Library construction, 3 October 1932."}); 
index.addDoc({"lunr_id":33,"link":"{{ site.baseurl }}/photos/39/","pid":"39","_title":"Consulting Rare Publications","_date":"between 1934 and 2009","_format":"photographs","_name":"","_subjects":"Academic libraries; New York (N.Y.)","_summary":"A student working with some of the rare publications dealing with the Russian Revolutionary Movement, purchased by Columbia University from funds granted by the Rockefeller Foundation."}); 
index.addDoc({"lunr_id":34,"link":"{{ site.baseurl }}/photos/4/","pid":"4","_title":"Butler Library Construction Pit","_date":"before 1931","_format":"photographs","_name":"","_subjects":"Academic libraries; New York (N.Y.)","_summary":"View of the construction pit on the site of the future Butler Library."}); 
index.addDoc({"lunr_id":35,"link":"{{ site.baseurl }}/photos/40/","pid":"40","_title":"Brander Matthews Hall","_date":"circa 1940","_format":"photographs","_name":"Gottscho, Samuel H. (Samuel Herman), 1875-1971","_subjects":"College buildings; Columbia University","_summary":""}); 
index.addDoc({"lunr_id":36,"link":"{{ site.baseurl }}/photos/41/","pid":"41","_title":"Commencement 1957","_date":"1957","_format":"photographs","_name":"","_subjects":"Academic libraries; New York (N.Y.); Butler Library","_summary":"View of Butler Library from Low Library entrance, during the 1957 commencement."}); 
index.addDoc({"lunr_id":37,"link":"{{ site.baseurl }}/photos/42/","pid":"42","_title":"Butler Library of Philosophy","_date":"circa 1934","_format":"photographs","_name":"Wurts Bros. (New York, N.Y.)","_subjects":"Academic libraries; Reading rooms; New York (N.Y.); Butler Library","_summary":"View of the Butler Library of Philosophy located in South Hall (Butler Library), ca. 1934."}); 
index.addDoc({"lunr_id":38,"link":"{{ site.baseurl }}/photos/43/","pid":"43","_title":"Catalogue Room","_date":"circa 1934","_format":"photographs","_name":"Wurts Bros. (New York, N.Y.)","_subjects":"Academic libraries; Card catalogs; New York (N.Y.); Butler Library","_summary":"View of patrons consulting the card catalog in the Catalogue Room, ca. 1934."}); 
index.addDoc({"lunr_id":39,"link":"{{ site.baseurl }}/photos/44/","pid":"44","_title":"Butler Library Construction 10","_date":"15-Aug-32","_format":"photographs","_name":"Beals, A. Tennyson","_subjects":"Academic libraries; New York (N.Y.); Butler Library","_summary":"Butler Library construction, 15 August 1932"}); 
index.addDoc({"lunr_id":40,"link":"{{ site.baseurl }}/photos/45/","pid":"45","_title":"College Library Reading Room","_date":"between 1934 and 2009","_format":"photographs","_name":"Warman, Manny, -1983","_subjects":"Academic libraries; Reading rooms; New York (N.Y.); Butler Library","_summary":"Students studying in College Library reading room (now Room 209)."}); 
index.addDoc({"lunr_id":41,"link":"{{ site.baseurl }}/photos/46/","pid":"46","_title":"Butler Library Construction 13","_date":"19-Sep-32","_format":"photographs","_name":"Beals, A. Tennyson","_subjects":"Academic libraries; New York (N.Y.); Butler Library","_summary":"Butler Library construction, 19 September 1932."}); 
index.addDoc({"lunr_id":42,"link":"{{ site.baseurl }}/photos/47/","pid":"47","_title":"Butler Library Construction 6","_date":"Jun-32","_format":"photographs","_name":"Beals, A. Tennyson","_subjects":"Academic libraries; New York (N.Y.); Butler Library","_summary":"Butler Library construction, June 1932."}); 
index.addDoc({"lunr_id":43,"link":"{{ site.baseurl }}/photos/48/","pid":"48","_title":"Butler Library Construction 21","_date":"6-Feb-33","_format":"photographs","_name":"Beals, A. Tennyson","_subjects":"Academic libraries; New York (N.Y.); Butler Library","_summary":"Butler Library construction, 6 February 1933."}); 
index.addDoc({"lunr_id":44,"link":"{{ site.baseurl }}/photos/49/","pid":"49","_title":"Book Chute","_date":"between 1934 and 2009","_format":"photographs","_name":"","_subjects":"Academic libraries; New York (N.Y.)","_summary":"Delivery desk station near a book conveyor with gravity discharge in South Hall (Butler Library)"}); 
index.addDoc({"lunr_id":45,"link":"{{ site.baseurl }}/photos/5/","pid":"5","_title":"College Library Reading Room Artwork","_date":"between 1934 and 2009","_format":"photographs","_name":"Warman, Manny, -1983","_subjects":"Academic libraries; Reading rooms; New York (N.Y.); Butler Library","_summary":"View of artwork on wall in the College Library reading room."}); 
index.addDoc({"lunr_id":46,"link":"{{ site.baseurl }}/photos/50/","pid":"50","_title":"Butler Library Exterior Lamp","_date":"between 1934 and 2009","_format":"photographs","_name":"","_subjects":"Academic libraries; New York (N.Y.)","_summary":"View from below of one of the exterior light fixtures on the front of Butler Library."}); 
index.addDoc({"lunr_id":47,"link":"{{ site.baseurl }}/photos/51/","pid":"51","_title":"Butler Library Construction 19","_date":"5-Jan-33","_format":"photographs","_name":"Beals, A. Tennyson","_subjects":"Academic libraries; New York (N.Y.); Butler Library","_summary":"Butler Library construction 5 January 1933."}); 
index.addDoc({"lunr_id":48,"link":"{{ site.baseurl }}/photos/52/","pid":"52","_title":"Butler Library Construction 1","_date":"14-May-32","_format":"photographs","_name":"Beals, A. Tennyson","_subjects":"Academic libraries; New York (N.Y.); Butler Library","_summary":"Butler Library construction, 14 May 1932."}); 
index.addDoc({"lunr_id":49,"link":"{{ site.baseurl }}/photos/53/","pid":"53","_title":"Butler Library Painted Red","_date":"25-Sep-36","_format":"photographs","_name":"Associated Press","_subjects":"Academic libraries; Vandalism; New York (N.Y.); Butler Library","_summary":"'While Columbia University guards were lunching early today [September 25, 1936], a well-organized squad of vandals daubed this red curtain of paint on the university's new library. Work was believed done either by painters' union or students sympathizing with Bob Burke expulsion. Paint is stain that 'sticks.''"}); 
index.addDoc({"lunr_id":50,"link":"{{ site.baseurl }}/photos/54/","pid":"54","_title":"Butler Library Construction 11","_date":"26-Aug-32","_format":"photographs","_name":"Beals, A. Tennyson","_subjects":"Academic libraries; New York (N.Y.); Butler Library","_summary":"Butler Library construction, 26 August 1932."}); 
index.addDoc({"lunr_id":51,"link":"{{ site.baseurl }}/photos/55/","pid":"55","_title":"Butler Library Entrance","_date":"between 1934 and 2009","_format":"photographs","_name":"","_subjects":"Academic libraries; New York (N.Y.); Butler Library","_summary":"View of Butler Library main entrance, with a Columbia security vehicle and a kid in the foreground."}); 
index.addDoc({"lunr_id":52,"link":"{{ site.baseurl }}/photos/56/","pid":"56","_title":"Butler Library Construction 2","_date":"6-Jun-32","_format":"photographs","_name":"Beals, A. Tennyson","_subjects":"Academic libraries; New York (N.Y.); Butler Library","_summary":"Butler Library construction, 6 June 1932."}); 
index.addDoc({"lunr_id":53,"link":"{{ site.baseurl }}/photos/57/","pid":"57","_title":"Craftsmanship Award Presentation","_date":"1934","_format":"photographs","_name":"Rothschild, Albert","_subjects":"Academic libraries; Award presentations; New York (N.Y.); Butler Library","_summary":"President Nicholas Murray Butler handing out a Craftsmanship Award in front of South Hall (Butler Library), 1934."}); 
index.addDoc({"lunr_id":54,"link":"{{ site.baseurl }}/photos/58/","pid":"58","_title":"Ball Playing in Front of Butler","_date":"between 1934 and 2009","_format":"photographs","_name":"","_subjects":"Academic libraries; New York (N.Y.); Butler Library","_summary":"Students playing football or possible rugby on lawn in front of Journalism Building with Butler Library in the background."}); 
index.addDoc({"lunr_id":55,"link":"{{ site.baseurl }}/photos/59/","pid":"59","_title":"Craftsmanship Award Winners","_date":"1934","_format":"photographs","_name":"Rothschild, Albert","_subjects":"Academic libraries; Award presentations; New York (N.Y.); Butler Library","_summary":"Group photograph of the 1934 Craftsmanship Award winners with President Nicholas Murray Butler in front of South Hall (Butler Library)."}); 
index.addDoc({"lunr_id":56,"link":"{{ site.baseurl }}/photos/6/","pid":"6","_title":"Butler Library at Night","_date":"1941","_format":"photographs","_name":"Alumni Federation of Columbia University","_subjects":"Academic libraries; New York (N.Y.); Butler Library","_summary":"South Hall (Butler Library) at night, 1941."}); 
index.addDoc({"lunr_id":57,"link":"{{ site.baseurl }}/photos/60/","pid":"60","_title":"Examining Papyrus","_date":"between 1934 and 2009","_format":"photographs","_name":"Bubley, Esther","_subjects":"Manuscripts (Papyri); Scholars; New York (N.Y.)","_summary":"Two scholars (one of whom is Professor John Day) looking at papyrus with magnifying glass in the Rare Book and Manuscript Library."}); 
index.addDoc({"lunr_id":58,"link":"{{ site.baseurl }}/photos/61/","pid":"61","_title":"Banjo Club, 1894-95","_date":"circa 1896","_format":"photographs","_name":"Pach Brothers (Firm)","_subjects":"College musicals; Banjoists; Columbia University","_summary":""}); 
index.addDoc({"lunr_id":59,"link":"{{ site.baseurl }}/photos/62/","pid":"62","_title":"Commencement Procession","_date":"1977","_format":"photographs","_name":"","_subjects":"Academic libraries; New York (N.Y.); Butler Library","_summary":"18 May 1977 Commencement ceremony. Procession of University Trustees from Butler Library to Low Plaza."}); 
index.addDoc({"lunr_id":60,"link":"{{ site.baseurl }}/photos/63/","pid":"63","_title":"Columbia Bicentennial Coverage","_date":"1954","_format":"photographs","_name":"","_subjects":"Academic libraries; New York (N.Y.)","_summary":"Woman looking at bulletin board containing examples of the media coverage for Columbia University's Bicentennial in 1954."}); 
index.addDoc({"lunr_id":61,"link":"{{ site.baseurl }}/photos/64/","pid":"64","_title":"Butler Library Construction 27","_date":"10-Aug-33","_format":"photographs","_name":"Beals, A. Tennyson","_subjects":"Academic libraries; New York (N.Y.); Butler Library","_summary":"Butler Library construction, 10 August 1933."}); 
index.addDoc({"lunr_id":62,"link":"{{ site.baseurl }}/photos/65/","pid":"65","_title":"Butler Library (South Hall) Completed","_date":"1934","_format":"photographs","_name":"Beals, A. Tennyson","_subjects":"Academic libraries; New York (N.Y.); Butler Library","_summary":"View of completed South Hall (Butler Library), 1934."}); 
index.addDoc({"lunr_id":63,"link":"{{ site.baseurl }}/photos/66/","pid":"66","_title":"Butler Library Construction 23","_date":"20-Apr-33","_format":"photographs","_name":"Beals, A. Tennyson","_subjects":"Academic libraries; New York (N.Y.); Butler Library","_summary":"Butler Library construction, 20 April 1933."}); 
index.addDoc({"lunr_id":64,"link":"{{ site.baseurl }}/photos/67/","pid":"67","_title":"Cataloging Librarian","_date":"between 1934 and 2009","_format":"photographs","_name":"Hartmann, Erich, 1922 July 29-; Magnum Photos","_subjects":"Academic libraries; Library employees; New York (N.Y.)","_summary":"Image of a cataloging librarian at work behind two carousels of _date stamps."}); 
index.addDoc({"lunr_id":65,"link":"{{ site.baseurl }}/photos/68/","pid":"68","_title":"Consulting the Card Catalog","_date":"between 1934 and 2009","_format":"photographs","_name":"Bubley, Esther","_subjects":"Card catalogs; Priests; New York (N.Y.); Butler Library","_summary":"Image of a priest looking through card catalog."}); 
index.addDoc({"lunr_id":66,"link":"{{ site.baseurl }}/photos/69/","pid":"69","_title":"Business Library Reading Room","_date":"between 1934 and 2009","_format":"photographs","_name":"Warman, Manny, -1983","_subjects":"Academic libraries; Reading rooms; New York (N.Y.); Butler Library","_summary":"View of students in the Business Library reading room located in Butler Library."}); 
index.addDoc({"lunr_id":67,"link":"{{ site.baseurl }}/photos/7/","pid":"7","_title":"For Columbia Theater, A Festive First Night,' Article in the New York Times, September 17, 1988.","_date":"17-Sep-88","_format":"clippings","_name":"Kozinn, Allan; New York times","_subjects":"Theaters; Columbia University","_summary":"Photocopy of clipping from New York Times"}); 
index.addDoc({"lunr_id":68,"link":"{{ site.baseurl }}/photos/70/","pid":"70","_title":"Butler Library Construction 25","_date":"19-May-33","_format":"photographs","_name":"Beals, A. Tennyson","_subjects":"Academic libraries; New York (N.Y.); Butler Library","_summary":"Butler Library construction, 19 May 1933."}); 
index.addDoc({"lunr_id":69,"link":"{{ site.baseurl }}/photos/71/","pid":"71","_title":"Business Library Reading Room","_date":"circa 1934","_format":"photographs","_name":"Wurts Bros. (New York, N.Y.)","_subjects":"Academic libraries; Reading rooms; New York (N.Y.); Butler Library","_summary":"View of the Business Library Reading Room in South Hall (Butler Library), ca. 1934."}); 
index.addDoc({"lunr_id":70,"link":"{{ site.baseurl }}/photos/72/","pid":"72","_title":"Butler Library Construction 18","_date":"22-Dec-32","_format":"photographs","_name":"Beals, A. Tennyson","_subjects":"Academic libraries; New York (N.Y.); Butler Library","_summary":"Butler Library construction, 22 December 1932."}); 
index.addDoc({"lunr_id":71,"link":"{{ site.baseurl }}/photos/73/","pid":"73","_title":"Butler Library from Low Library Entrance","_date":"between 1934 and 2009","_format":"photographs","_name":"","_subjects":"Academic libraries; New York (N.Y.); Butler Library","_summary":"View of Butler Library as seen from the entrance of Low Memorial Library."}); 
index.addDoc({"lunr_id":72,"link":"{{ site.baseurl }}/photos/74/","pid":"74","_title":"Butler Library Construction 22","_date":"9-Mar-33","_format":"photographs","_name":"Beals, A. Tennyson","_subjects":"Academic libraries; New York (N.Y.); Butler Library","_summary":"Butler Library construction, 9 March 1933."}); 
index.addDoc({"lunr_id":73,"link":"{{ site.baseurl }}/photos/75/","pid":"75","_title":"Conservation Work Room","_date":"between 1934 and 2009","_format":"photographs","_name":"","_subjects":"Academic libraries; New York (N.Y.); Butler Library","_summary":"View of equipment in the Conservation work room."}); 
index.addDoc({"lunr_id":74,"link":"{{ site.baseurl }}/photos/76/","pid":"76","_title":"Book Transfer","_date":"between August 20 and September 19, 1934","_format":"photographs","_name":"Sprague","_subjects":"College campuses; New York (N.Y.)","_summary":"View of one portion of the book conveyor system from behind the Alma Mater statue on Low Plaza. Between August 20 and September 19, 1934 student workers and professional movers moved books from their original home in Low Library to their new home in South Hall (Butler Library)."}); 
index.addDoc({"lunr_id":75,"link":"{{ site.baseurl }}/photos/77/","pid":"77","_title":"Butler Library Construction 3","_date":"15-Jun-32","_format":"photographs","_name":"Beals, A. Tennyson","_subjects":"Academic libraries; New York (N.Y.); Butler Library","_summary":"Butler Library construction, 15 June 1932."}); 
index.addDoc({"lunr_id":76,"link":"{{ site.baseurl }}/photos/78/","pid":"78","_title":"Conservation Work Room","_date":"between 1934 and 2009","_format":"photographs","_name":"","_subjects":"Academic libraries; New York (N.Y.); Butler Library","_summary":"View of staff work spaces in the Conservation work room."}); 
index.addDoc({"lunr_id":77,"link":"{{ site.baseurl }}/photos/79/","pid":"79","_title":"Butler Library Construction 5","_date":"28-Jun-32","_format":"photographs","_name":"Beals, A. Tennyson","_subjects":"Academic libraries; New York (N.Y.); Butler Library","_summary":"Butler Library construction, 28 June 1932."}); 
index.addDoc({"lunr_id":78,"link":"{{ site.baseurl }}/photos/8/","pid":"8","_title":"Butler Library Office","_date":"between 1934 and 2009","_format":"photographs","_name":"","_subjects":"Academic libraries; New York (N.Y.); Butler Library","_summary":"View inside an office inside Butler Library on the third floor."}); 
index.addDoc({"lunr_id":79,"link":"{{ site.baseurl }}/photos/80/","pid":"80","_title":"Checking Sources","_date":"between 1934 and 2009","_format":"photographs","_name":"Warman, Manny, -1983","_subjects":"Academic libraries; College students; New York (N.Y.)","_summary":"'Theodore Shabad, assistant editor of the Gazetteer, checks data on source which include a Communist atlas published in 1950, and the China Postal Guide in both Chinese and English editions. '"}); 
index.addDoc({"lunr_id":80,"link":"{{ site.baseurl }}/photos/81/","pid":"81","_title":"Butler Library - Looking West","_date":"between 1934 and 2009","_format":"photographs","_name":"Warman, Manny, -1983","_subjects":"Academic libraries; New York (N.Y.); Butler Library","_summary":"View of Butler Library through foliage and a fence, looking west."}); 
index.addDoc({"lunr_id":81,"link":"{{ site.baseurl }}/photos/82/","pid":"82","_title":"Butler Library Construction 8","_date":"21-Jul-32","_format":"photographs","_name":"Beals, A. Tennyson","_subjects":"Academic libraries; New York (N.Y.); Butler Library","_summary":"Butler Library construction, 21 July 1932."}); 
index.addDoc({"lunr_id":82,"link":"{{ site.baseurl }}/photos/83/","pid":"83","_title":"Conservation Work Room","_date":"between 1934 and 2009","_format":"photographs","_name":"","_subjects":"Academic libraries; New York (N.Y.); Butler Library","_summary":"View of paper rolls in the Conservation department work room."}); 
index.addDoc({"lunr_id":83,"link":"{{ site.baseurl }}/photos/84/","pid":"84","_title":"Browsing Room","_date":"between 1934 and 2009","_format":"photographs","_name":"","_subjects":"Academic libraries; New York (N.Y.); Butler Library","_summary":"View of students in Butler Library's Browsing Room."}); 
index.addDoc({"lunr_id":84,"link":"{{ site.baseurl }}/photos/85/","pid":"85","_title":"Commencement 1953","_date":"1953","_format":"photographs","_name":"","_subjects":"Academic libraries; New York (N.Y.); Butler Library","_summary":"1953 Columbia graduate, holding two children, having his picture taken after the ceremony is over."}); 
index.addDoc({"lunr_id":85,"link":"{{ site.baseurl }}/photos/86/","pid":"86","_title":"Browsing Room","_date":"circa 1934","_format":"photographs","_name":"Wurts Bros. (New York, N.Y.)","_subjects":"Academic libraries; Reading rooms; New York (N.Y.); Butler Library","_summary":"View of South Hall (Butler Library) browsing room, ca. 1934."}); 
index.addDoc({"lunr_id":86,"link":"{{ site.baseurl }}/photos/87/","pid":"87","_title":"Binding Department","_date":"between 1934 and 2009","_format":"photographs","_name":"Ballou, Hubbard W.","_subjects":"Academic libraries; Bookbinding; New York (N.Y.); Butler Library","_summary":"Employees at work in the binding room with piles of books everywhere."}); 
index.addDoc({"lunr_id":87,"link":"{{ site.baseurl }}/photos/88/","pid":"88","_title":"Butler Library Construction 17","_date":"7-Dec-32","_format":"photographs","_name":"Beals, A. Tennyson","_subjects":"Academic libraries; New York (N.Y.); Butler Library","_summary":"Butler Library construction, 7 December 1932."}); 
index.addDoc({"lunr_id":88,"link":"{{ site.baseurl }}/photos/89/","pid":"89","_title":"Alcove in Browsing Room","_date":"circa 1934","_format":"photographs","_name":"Wurts Bros. (New York, N.Y.)","_subjects":"Academic libraries; Reading rooms; New York (N.Y.); Butler Library","_summary":"View of people sitting in an alcove in South Hall (Butler Library) browsing room, ca. 1934."}); 
index.addDoc({"lunr_id":89,"link":"{{ site.baseurl }}/photos/9/","pid":"9","_title":"General View of Columbia University","_date":"1898","_format":"photographs","_name":"Geo. P. Hall & Son","_subjects":"Columbia University; Low Memorial Library","_summary":""}); 
index.addDoc({"lunr_id":90,"link":"{{ site.baseurl }}/photos/90/","pid":"90","_title":"Butler Library Construction 24","_date":"5-Apr-33","_format":"photographs","_name":"Beals, A. Tennyson","_subjects":"Academic libraries; New York (N.Y.); Butler Library","_summary":"Butler Library construction, 5 April 1933."}); 
index.addDoc({"lunr_id":91,"link":"{{ site.baseurl }}/photos/91/","pid":"91","_title":"Butler Library from Avery","_date":"8-Sep-37","_format":"photographs","_name":"Bogert, W.L.","_subjects":"Academic libraries; New York (N.Y.); Butler Library","_summary":"View of Butler Library as seen from steps of Avery Library, 8 September 1937."}); 
index.addDoc({"lunr_id":92,"link":"{{ site.baseurl }}/photos/92/","pid":"92","_title":"Butler Library Construction 16","_date":"25-Nov-32","_format":"photographs","_name":"Beals, A. Tennyson","_subjects":"Academic libraries; New York (N.Y.); Butler Library","_summary":"Butler Library construction, 25 November 1932."}); 
index.addDoc({"lunr_id":93,"link":"{{ site.baseurl }}/photos/93/","pid":"93","_title":"Banned Books' Display","_date":"1954","_format":"photographs","_name":"Warman, Manny, -1983","_subjects":"Academic libraries; Prohibited books; New York (N.Y.)","_summary":"'Students pore over a display of 'Banned Books of All Ages' in Butler Library at Columbia University which is observing its 200th anniversary throughout 1954.'"}); 
index.addDoc({"lunr_id":94,"link":"{{ site.baseurl }}/photos/94/","pid":"94","_title":"College Study - Butler Library","_date":"between 1934 and 2009","_format":"photographs","_name":"","_subjects":"Academic libraries; New York (N.Y.); Butler Library","_summary":"View of students in the College Study located within Butler Library."}); 
index.addDoc({"lunr_id":95,"link":"{{ site.baseurl }}/photos/95/","pid":"95","_title":"Butler Library Construction 7","_date":"8-Jul-32","_format":"photographs","_name":"Beals, A. Tennyson","_subjects":"Academic libraries; New York (N.Y.); Butler Library","_summary":"Butler Library construction, 8 July 1932."}); 
index.addDoc({"lunr_id":96,"link":"{{ site.baseurl }}/photos/96/","pid":"96","_title":"Bonfire in Front of Butler Library","_date":"circa 1940-1949","_format":"photographs","_name":"Hopp, Morris J.","_subjects":"Academic libraries; Bonfires; New York (N.Y.); Butler Library","_summary":"Wide view of bonfire in front of Butler Library, ca. 1940s."}); 
index.addDoc({"lunr_id":97,"link":"{{ site.baseurl }}/photos/97/","pid":"97","_title":"Butler Library Construction 9","_date":"4-Aug-32","_format":"photographs","_name":"Beals, A. Tennyson","_subjects":"Academic libraries; New York (N.Y.); Butler Library","_summary":"Butler Library construction, 4 August 1932."}); 
index.addDoc({"lunr_id":98,"link":"{{ site.baseurl }}/photos/98/","pid":"98","_title":"Frosh-Soph Tug of War","_date":"between 1934 and 2009","_format":"photographs","_name":"","_subjects":"Academic libraries; New York (N.Y.); Butler Library","_summary":"Tug of war for Soph-Frosh Rush taking place in front of Butler Library."}); 
index.addDoc({"lunr_id":99,"link":"{{ site.baseurl }}/photos/99/","pid":"99","_title":"Butler Library Construction 15","_date":"22-Oct-32","_format":"photographs","_name":"Beals, A. Tennyson","_subjects":"Academic libraries; New York (N.Y.); Butler Library","_summary":"Butler Library construction, 22 October 1932."}); 
var store = [
{"lunr_id":0,"link":"{{ site.baseurl }}/photos/1/","pid":"1","_title":"Butler Library - Looking West","_date":"1934","_format":"photographs","_name":"Warman, Manny, -1983","_subjects":"Academic libraries; New York (N.Y.); Butler Library","_summary":"View of Butler Library through foliage and a fence, looking west, 1934."}, 
{"lunr_id":1,"link":"{{ site.baseurl }}/photos/10/","pid":"10","_title":"Butler Library Exterior Lamp","_date":"circa 1933-1934","_format":"photographs","_name":"Beals, A. Tennyson","_subjects":"Academic libraries; New York (N.Y.); Butler Library","_summary":"View of one of the light fixtures on the outside of Butler Library, ca. 1933-34."}, 
{"lunr_id":2,"link":"{{ site.baseurl }}/photos/100/","pid":"100","_title":"Columbia Bicentennial Display","_date":"between 1934 and 2009","_format":"photographs","_name":"Warman, Manny, -1983","_subjects":"Academic libraries; Women college students; New York (N.Y.)","_summary":"'Students discuss one of the panels in Columbia University's Bicentennial Exhibit entitled 'A Man's Right to Knowledge and the Free Use Thereof.' A funereal design surrounds a photograph showing the damaged front of the office of La Prensa, the opposition newspaper in Buenos Aires, Argentina, closed by order of Juan Peron, January 26, 1951. The quotation from John Locke reads: '...if what (a man) holds be, as he gives out, well fenced with evidence, and he sees it to be true, what need he fear to put it to the proof?...He whose assent goes beyond his evidence owes this excess of his adherence only to prejudice, and does, in effect, own it....declaring thereby that it is not evidence he seeks but the quiet enjoyment of the opinion he is fond of...''"}, 
{"lunr_id":3,"link":"{{ site.baseurl }}/photos/11/","pid":"11","_title":"Butler Library - Looking West","_date":"between 1934 and 2009","_format":"photographs","_name":"","_subjects":"Academic libraries; New York (N.Y.); Butler Library","_summary":"View of Butler Library through foliage, looking west."}, 
{"lunr_id":4,"link":"{{ site.baseurl }}/photos/12/","pid":"12","_title":"Consulting the Card Catalog","_date":"between 1934 and 2009","_format":"photographs","_name":"","_subjects":"Academic libraries; New York (N.Y.); Butler Library","_summary":"Image of patrons using the card catalog in Butler Library."}, 
{"lunr_id":5,"link":"{{ site.baseurl }}/photos/13/","pid":"13","_title":"College Reading Room","_date":"between 1934 and 2009","_format":"photographs","_name":"","_subjects":"Academic libraries; New York (N.Y.); Butler Library","_summary":"View of the college reading room (226 Butler Library)."}, 
{"lunr_id":6,"link":"{{ site.baseurl }}/photos/14/","pid":"14","_title":"Cataloging Room","_date":"between 1934 and 2009","_format":"photographs","_name":"Ballou, Hubbard W.","_subjects":"Academic libraries; Cataloging; New York (N.Y.); Butler Library","_summary":"Overhead view of the cataloging room."}, 
{"lunr_id":7,"link":"{{ site.baseurl }}/photos/15/","pid":"15","_title":"Columbia Encyclopedia Publication Party","_date":"between 1934 and 2009","_format":"photographs","_name":"Warman, Manny, -1983","_subjects":"Academic libraries; New York (N.Y.)","_summary":"Professor Tyndall and Dwight Miner at the publication party for the Columbia Encyclopedia."}, 
{"lunr_id":8,"link":"{{ site.baseurl }}/photos/16/","pid":"16","_title":"Browsing Room, December 1945","_date":"December, 1945","_format":"photographs","_name":"","_subjects":"Academic libraries; New York (N.Y.); Butler Library","_summary":"Students in the Butler Library Browsing Room, December 1945."}, 
{"lunr_id":9,"link":"{{ site.baseurl }}/photos/17/","pid":"17","_title":"Butler Library Construction 26","_date":"1-Jun-33","_format":"photographs","_name":"Beals, A. Tennyson","_subjects":"Academic libraries; New York (N.Y.); Butler Library","_summary":"Butler Library construction, 1 June 1933."}, 
{"lunr_id":10,"link":"{{ site.baseurl }}/photos/18/","pid":"18","_title":"Film Editing","_date":"circa 1947","_format":"photographs","_name":"","_subjects":"Academic libraries; New York (N.Y.)","_summary":"CMC (Columbia Movie Club?) members editing film, ca. 1947."}, 
{"lunr_id":11,"link":"{{ site.baseurl }}/photos/19/","pid":"19","_title":"Butler Library at Night","_date":"November, 1937","_format":"photographs","_name":"Janovsky, Seymour","_subjects":"Academic libraries; Butler Library; New York (N.Y.); Butler Library","_summary":"View of Butler Library at night as viewed from across 116th Street, November 1937."}, 
{"lunr_id":12,"link":"{{ site.baseurl }}/photos/2/","pid":"2","_title":"Butler Library Construction 29","_date":"7-Oct-33","_format":"photographs","_name":"Beals, A. Tennyson","_subjects":"Academic libraries; New York (N.Y.); Butler Library","_summary":"Butler Library construction, 7 October 1933."}, 
{"lunr_id":13,"link":"{{ site.baseurl }}/photos/20/","pid":"20","_title":"Butler Library Construction 20","_date":"20-Jan-33","_format":"photographs","_name":"Beals, A. Tennyson","_subjects":"Academic libraries; New York (N.Y.); Butler Library","_summary":"Butler Library construction, 20 January 1933."}, 
{"lunr_id":14,"link":"{{ site.baseurl }}/photos/21/","pid":"21","_title":"Book Transfer","_date":"31-Aug-34","_format":"photographs","_name":"Boldtman, J.","_subjects":"College campuses; New York (N.Y.)","_summary":"31 August 1934. Boxes of books loaded onto the book chute next to the Alma Mater on their way across campus. Between August 20 and September 19, 1934 student workers and professional movers moved books from their original home in Low Library to their new home in South Hall (Butler Library)."}, 
{"lunr_id":15,"link":"{{ site.baseurl }}/photos/22/","pid":"22","_title":"Butler Library at Dusk","_date":"between 1934 and 2009","_format":"photographs","_name":"Warman, Manny, -1983","_subjects":"Academic libraries; New York (N.Y.); Butler Library","_summary":"View of Butler Library at dusk from across 116th Street, looking south."}, 
{"lunr_id":16,"link":"{{ site.baseurl }}/photos/23/","pid":"23","_title":"Ceiling-Butler Library","_date":"circa 1934","_format":"photographs","_name":"Wurts Bros. (New York, N.Y.)","_subjects":"Academic libraries; Decoration and ornament; New York (N.Y.); Butler Library","_summary":"Detail view of the ceiling in the Butler Library of Philosophy located in South Hall (Butler Library), ca. 1934."}, 
{"lunr_id":17,"link":"{{ site.baseurl }}/photos/24/","pid":"24","_title":"Book Transfer","_date":"between August 20 and September 19, 1934","_format":"photographs","_name":"Sprague","_subjects":"College campuses; New York (N.Y.)","_summary":"Image of student workers moving boxes from book chutes onto book carts at the foot of stairs to Low Plaza. Between August 20 and September 19, 1934 student workers and professional movers moved books from their original home in Low Library to their new home in South Hall (Butler Library)."}, 
{"lunr_id":18,"link":"{{ site.baseurl }}/photos/25/","pid":"25","_title":"Browsing Room","_date":"between 1934 and 2009","_format":"photographs","_name":"Bubley, Esther","_subjects":"Academic libraries; College students; New York (N.Y.); Butler Library","_summary":"Students in Butler Library's Browsing Room."}, 
{"lunr_id":19,"link":"{{ site.baseurl }}/photos/26/","pid":"26","_title":"Butler Library Stacks","_date":"circa 1934-1939","_format":"photographs","_name":"","_subjects":"Academic libraries; New York (N.Y.); Butler Library","_summary":"Main transverse stack aisle showing continuous beam less ceiling and tile covered floor, ca. 1930s."}, 
{"lunr_id":20,"link":"{{ site.baseurl }}/photos/27/","pid":"27","_title":"Columbia' Gate","_date":"between 1934 and 2009","_format":"photographs","_name":"Bubley, Esther","_subjects":"Academic libraries; New York (N.Y.); Butler Library","_summary":"Students walking through 'Columbia' gate on the main level of Butler Library."}, 
{"lunr_id":21,"link":"{{ site.baseurl }}/photos/28/","pid":"28","_title":"Butler Library - Main entrance mural","_date":"between 1934 and 2009","_format":"photographs","_name":"Look magazine","_subjects":"Academic libraries; Mural painting and decoration; New York (N.Y.); Butler Library","_summary":"Man and woman on bench in front of the main entrance mural of Athene painted by Eugene Savage of the Yale School of Fine Arts. Attributed to Look Magazine"}, 
{"lunr_id":22,"link":"{{ site.baseurl }}/photos/29/","pid":"29","_title":"Butler Library Construction Pit","_date":"before 1931","_format":"photographs","_name":"Boldtman, J.","_subjects":"College campuses; Building; New York (N.Y.)","_summary":"View of the construction pit on the site of the future Butler Library."}, 
{"lunr_id":23,"link":"{{ site.baseurl }}/photos/3/","pid":"3","_title":"Book Returns to Columbia Library After 178 Years","_date":"6-Sep-50","_format":"photographs","_name":"Warman, Manny, -1983","_subjects":"Academic libraries; New York (N.Y.)","_summary":"Enos M. Johnson (left) of Brooklyn, hands rare volume over to Dr. Richard H. Logsdon, associate director of the Columbia University Libraries. The book, entitled 'A System of Natural Philosophy,' was drawn from the shelves of the old King's College library in 1772 -- a dozen years before King's College became Columbia. It was recently discovered by Mr. Johnston as he rummaged through the attic at the home of his aunt, Miss Susan Ruggles of Binghamton, N.Y. The scholar who borrowed the book was Robert Harpur, one-time librarian of King's College and tutor of Alexander Hamilton. It was not regarded as 'overdue' at the University library, which was fortunate in view of the fact that a considerable fine would have been in order. The fine, calculated at the rate of five cents per day, would have totaled $3,248.50. Dr. Logsdon expressed the Library's gratitude for the return of the volume. 'The Library is especially happy to have this historic volume come back into its possession,' said Dr. Logsdon. 'We are most grateful to Mr. Johnston. The book, spanning virtually all of Columbia's life through nearly two centuries of American history, will serves as an interesting item for exhibition in Columbia's coming Bicentennial celebration in 1954.' (from: press release attached to image)"}, 
{"lunr_id":24,"link":"{{ site.baseurl }}/photos/30/","pid":"30","_title":"Butler Library Construction 4","_date":"15-Jun-32","_format":"photographs","_name":"Beals, A. Tennyson","_subjects":"Academic libraries; New York (N.Y.); Butler Library","_summary":"Butler Library construction, 15 June 1932."}, 
{"lunr_id":25,"link":"{{ site.baseurl }}/photos/31/","pid":"31","_title":"Columbia University, New York","_date":"1902","_format":"postcards","_name":"","_subjects":"Columbia University","_summary":""}, 
{"lunr_id":26,"link":"{{ site.baseurl }}/photos/32/","pid":"32","_title":"Exhibit of French Universities at Butler Library","_date":"1954","_format":"photographs","_name":"","_subjects":"Academic libraries; New York (N.Y.); Butler Library","_summary":"Image of (L to R) Pierre Douzelot, President Grayson Kirk, Jean Sarrailk, and Henri Bonnet examining a part of the exhibit of French Universities at Butler Library, 18 October 1954."}, 
{"lunr_id":27,"link":"{{ site.baseurl }}/photos/33/","pid":"33","_title":"Butler Library Construction 12","_date":"7-Sep-32","_format":"photographs","_name":"Beals, A. Tennyson","_subjects":"Academic libraries; New York (N.Y.); Butler Library","_summary":"Butler Library construction, 7 September 1932."}, 
{"lunr_id":28,"link":"{{ site.baseurl }}/photos/34/","pid":"34","_title":"Book Sorting Shelves","_date":"between 1934 and 2009","_format":"photographs","_name":"","_subjects":"Academic libraries; New York (N.Y.)","_summary":"Books on book sorting shelves with sloping backs and bottoms."}, 
{"lunr_id":29,"link":"{{ site.baseurl }}/photos/35/","pid":"35","_title":"College Library Reading Room","_date":"between 1934 and 2009","_format":"photographs","_name":"Warman, Manny, -1983","_subjects":"Academic libraries; Reading rooms; New York (N.Y.); Butler Library","_summary":"College students studying in the reading room."}, 
{"lunr_id":30,"link":"{{ site.baseurl }}/photos/36/","pid":"36","_title":"Butler Library Construction 28","_date":"25-Oct-33","_format":"photographs","_name":"Beals, A. Tennyson","_subjects":"Academic libraries; New York (N.Y.); Butler Library","_summary":"Butler Library construction, 25 October 1933."}, 
{"lunr_id":31,"link":"{{ site.baseurl }}/photos/37/","pid":"37","_title":"Butler Library Front Door","_date":"between 1934 and 2009","_format":"photographs","_name":"Beals, A. Tennyson","_subjects":"Academic libraries; New York (N.Y.); Butler Library","_summary":"View of Butler Library's main entrance."}, 
{"lunr_id":32,"link":"{{ site.baseurl }}/photos/38/","pid":"38","_title":"Butler Library Construction 14","_date":"3-Oct-32","_format":"photographs","_name":"Beals, A. Tennyson","_subjects":"Academic libraries; New York (N.Y.); Butler Library","_summary":"Butler Library construction, 3 October 1932."}, 
{"lunr_id":33,"link":"{{ site.baseurl }}/photos/39/","pid":"39","_title":"Consulting Rare Publications","_date":"between 1934 and 2009","_format":"photographs","_name":"","_subjects":"Academic libraries; New York (N.Y.)","_summary":"A student working with some of the rare publications dealing with the Russian Revolutionary Movement, purchased by Columbia University from funds granted by the Rockefeller Foundation."}, 
{"lunr_id":34,"link":"{{ site.baseurl }}/photos/4/","pid":"4","_title":"Butler Library Construction Pit","_date":"before 1931","_format":"photographs","_name":"","_subjects":"Academic libraries; New York (N.Y.)","_summary":"View of the construction pit on the site of the future Butler Library."}, 
{"lunr_id":35,"link":"{{ site.baseurl }}/photos/40/","pid":"40","_title":"Brander Matthews Hall","_date":"circa 1940","_format":"photographs","_name":"Gottscho, Samuel H. (Samuel Herman), 1875-1971","_subjects":"College buildings; Columbia University","_summary":""}, 
{"lunr_id":36,"link":"{{ site.baseurl }}/photos/41/","pid":"41","_title":"Commencement 1957","_date":"1957","_format":"photographs","_name":"","_subjects":"Academic libraries; New York (N.Y.); Butler Library","_summary":"View of Butler Library from Low Library entrance, during the 1957 commencement."}, 
{"lunr_id":37,"link":"{{ site.baseurl }}/photos/42/","pid":"42","_title":"Butler Library of Philosophy","_date":"circa 1934","_format":"photographs","_name":"Wurts Bros. (New York, N.Y.)","_subjects":"Academic libraries; Reading rooms; New York (N.Y.); Butler Library","_summary":"View of the Butler Library of Philosophy located in South Hall (Butler Library), ca. 1934."}, 
{"lunr_id":38,"link":"{{ site.baseurl }}/photos/43/","pid":"43","_title":"Catalogue Room","_date":"circa 1934","_format":"photographs","_name":"Wurts Bros. (New York, N.Y.)","_subjects":"Academic libraries; Card catalogs; New York (N.Y.); Butler Library","_summary":"View of patrons consulting the card catalog in the Catalogue Room, ca. 1934."}, 
{"lunr_id":39,"link":"{{ site.baseurl }}/photos/44/","pid":"44","_title":"Butler Library Construction 10","_date":"15-Aug-32","_format":"photographs","_name":"Beals, A. Tennyson","_subjects":"Academic libraries; New York (N.Y.); Butler Library","_summary":"Butler Library construction, 15 August 1932"}, 
{"lunr_id":40,"link":"{{ site.baseurl }}/photos/45/","pid":"45","_title":"College Library Reading Room","_date":"between 1934 and 2009","_format":"photographs","_name":"Warman, Manny, -1983","_subjects":"Academic libraries; Reading rooms; New York (N.Y.); Butler Library","_summary":"Students studying in College Library reading room (now Room 209)."}, 
{"lunr_id":41,"link":"{{ site.baseurl }}/photos/46/","pid":"46","_title":"Butler Library Construction 13","_date":"19-Sep-32","_format":"photographs","_name":"Beals, A. Tennyson","_subjects":"Academic libraries; New York (N.Y.); Butler Library","_summary":"Butler Library construction, 19 September 1932."}, 
{"lunr_id":42,"link":"{{ site.baseurl }}/photos/47/","pid":"47","_title":"Butler Library Construction 6","_date":"Jun-32","_format":"photographs","_name":"Beals, A. Tennyson","_subjects":"Academic libraries; New York (N.Y.); Butler Library","_summary":"Butler Library construction, June 1932."}, 
{"lunr_id":43,"link":"{{ site.baseurl }}/photos/48/","pid":"48","_title":"Butler Library Construction 21","_date":"6-Feb-33","_format":"photographs","_name":"Beals, A. Tennyson","_subjects":"Academic libraries; New York (N.Y.); Butler Library","_summary":"Butler Library construction, 6 February 1933."}, 
{"lunr_id":44,"link":"{{ site.baseurl }}/photos/49/","pid":"49","_title":"Book Chute","_date":"between 1934 and 2009","_format":"photographs","_name":"","_subjects":"Academic libraries; New York (N.Y.)","_summary":"Delivery desk station near a book conveyor with gravity discharge in South Hall (Butler Library)"}, 
{"lunr_id":45,"link":"{{ site.baseurl }}/photos/5/","pid":"5","_title":"College Library Reading Room Artwork","_date":"between 1934 and 2009","_format":"photographs","_name":"Warman, Manny, -1983","_subjects":"Academic libraries; Reading rooms; New York (N.Y.); Butler Library","_summary":"View of artwork on wall in the College Library reading room."}, 
{"lunr_id":46,"link":"{{ site.baseurl }}/photos/50/","pid":"50","_title":"Butler Library Exterior Lamp","_date":"between 1934 and 2009","_format":"photographs","_name":"","_subjects":"Academic libraries; New York (N.Y.)","_summary":"View from below of one of the exterior light fixtures on the front of Butler Library."}, 
{"lunr_id":47,"link":"{{ site.baseurl }}/photos/51/","pid":"51","_title":"Butler Library Construction 19","_date":"5-Jan-33","_format":"photographs","_name":"Beals, A. Tennyson","_subjects":"Academic libraries; New York (N.Y.); Butler Library","_summary":"Butler Library construction 5 January 1933."}, 
{"lunr_id":48,"link":"{{ site.baseurl }}/photos/52/","pid":"52","_title":"Butler Library Construction 1","_date":"14-May-32","_format":"photographs","_name":"Beals, A. Tennyson","_subjects":"Academic libraries; New York (N.Y.); Butler Library","_summary":"Butler Library construction, 14 May 1932."}, 
{"lunr_id":49,"link":"{{ site.baseurl }}/photos/53/","pid":"53","_title":"Butler Library Painted Red","_date":"25-Sep-36","_format":"photographs","_name":"Associated Press","_subjects":"Academic libraries; Vandalism; New York (N.Y.); Butler Library","_summary":"'While Columbia University guards were lunching early today [September 25, 1936], a well-organized squad of vandals daubed this red curtain of paint on the university's new library. Work was believed done either by painters' union or students sympathizing with Bob Burke expulsion. Paint is stain that 'sticks.''"}, 
{"lunr_id":50,"link":"{{ site.baseurl }}/photos/54/","pid":"54","_title":"Butler Library Construction 11","_date":"26-Aug-32","_format":"photographs","_name":"Beals, A. Tennyson","_subjects":"Academic libraries; New York (N.Y.); Butler Library","_summary":"Butler Library construction, 26 August 1932."}, 
{"lunr_id":51,"link":"{{ site.baseurl }}/photos/55/","pid":"55","_title":"Butler Library Entrance","_date":"between 1934 and 2009","_format":"photographs","_name":"","_subjects":"Academic libraries; New York (N.Y.); Butler Library","_summary":"View of Butler Library main entrance, with a Columbia security vehicle and a kid in the foreground."}, 
{"lunr_id":52,"link":"{{ site.baseurl }}/photos/56/","pid":"56","_title":"Butler Library Construction 2","_date":"6-Jun-32","_format":"photographs","_name":"Beals, A. Tennyson","_subjects":"Academic libraries; New York (N.Y.); Butler Library","_summary":"Butler Library construction, 6 June 1932."}, 
{"lunr_id":53,"link":"{{ site.baseurl }}/photos/57/","pid":"57","_title":"Craftsmanship Award Presentation","_date":"1934","_format":"photographs","_name":"Rothschild, Albert","_subjects":"Academic libraries; Award presentations; New York (N.Y.); Butler Library","_summary":"President Nicholas Murray Butler handing out a Craftsmanship Award in front of South Hall (Butler Library), 1934."}, 
{"lunr_id":54,"link":"{{ site.baseurl }}/photos/58/","pid":"58","_title":"Ball Playing in Front of Butler","_date":"between 1934 and 2009","_format":"photographs","_name":"","_subjects":"Academic libraries; New York (N.Y.); Butler Library","_summary":"Students playing football or possible rugby on lawn in front of Journalism Building with Butler Library in the background."}, 
{"lunr_id":55,"link":"{{ site.baseurl }}/photos/59/","pid":"59","_title":"Craftsmanship Award Winners","_date":"1934","_format":"photographs","_name":"Rothschild, Albert","_subjects":"Academic libraries; Award presentations; New York (N.Y.); Butler Library","_summary":"Group photograph of the 1934 Craftsmanship Award winners with President Nicholas Murray Butler in front of South Hall (Butler Library)."}, 
{"lunr_id":56,"link":"{{ site.baseurl }}/photos/6/","pid":"6","_title":"Butler Library at Night","_date":"1941","_format":"photographs","_name":"Alumni Federation of Columbia University","_subjects":"Academic libraries; New York (N.Y.); Butler Library","_summary":"South Hall (Butler Library) at night, 1941."}, 
{"lunr_id":57,"link":"{{ site.baseurl }}/photos/60/","pid":"60","_title":"Examining Papyrus","_date":"between 1934 and 2009","_format":"photographs","_name":"Bubley, Esther","_subjects":"Manuscripts (Papyri); Scholars; New York (N.Y.)","_summary":"Two scholars (one of whom is Professor John Day) looking at papyrus with magnifying glass in the Rare Book and Manuscript Library."}, 
{"lunr_id":58,"link":"{{ site.baseurl }}/photos/61/","pid":"61","_title":"Banjo Club, 1894-95","_date":"circa 1896","_format":"photographs","_name":"Pach Brothers (Firm)","_subjects":"College musicals; Banjoists; Columbia University","_summary":""}, 
{"lunr_id":59,"link":"{{ site.baseurl }}/photos/62/","pid":"62","_title":"Commencement Procession","_date":"1977","_format":"photographs","_name":"","_subjects":"Academic libraries; New York (N.Y.); Butler Library","_summary":"18 May 1977 Commencement ceremony. Procession of University Trustees from Butler Library to Low Plaza."}, 
{"lunr_id":60,"link":"{{ site.baseurl }}/photos/63/","pid":"63","_title":"Columbia Bicentennial Coverage","_date":"1954","_format":"photographs","_name":"","_subjects":"Academic libraries; New York (N.Y.)","_summary":"Woman looking at bulletin board containing examples of the media coverage for Columbia University's Bicentennial in 1954."}, 
{"lunr_id":61,"link":"{{ site.baseurl }}/photos/64/","pid":"64","_title":"Butler Library Construction 27","_date":"10-Aug-33","_format":"photographs","_name":"Beals, A. Tennyson","_subjects":"Academic libraries; New York (N.Y.); Butler Library","_summary":"Butler Library construction, 10 August 1933."}, 
{"lunr_id":62,"link":"{{ site.baseurl }}/photos/65/","pid":"65","_title":"Butler Library (South Hall) Completed","_date":"1934","_format":"photographs","_name":"Beals, A. Tennyson","_subjects":"Academic libraries; New York (N.Y.); Butler Library","_summary":"View of completed South Hall (Butler Library), 1934."}, 
{"lunr_id":63,"link":"{{ site.baseurl }}/photos/66/","pid":"66","_title":"Butler Library Construction 23","_date":"20-Apr-33","_format":"photographs","_name":"Beals, A. Tennyson","_subjects":"Academic libraries; New York (N.Y.); Butler Library","_summary":"Butler Library construction, 20 April 1933."}, 
{"lunr_id":64,"link":"{{ site.baseurl }}/photos/67/","pid":"67","_title":"Cataloging Librarian","_date":"between 1934 and 2009","_format":"photographs","_name":"Hartmann, Erich, 1922 July 29-; Magnum Photos","_subjects":"Academic libraries; Library employees; New York (N.Y.)","_summary":"Image of a cataloging librarian at work behind two carousels of _date stamps."}, 
{"lunr_id":65,"link":"{{ site.baseurl }}/photos/68/","pid":"68","_title":"Consulting the Card Catalog","_date":"between 1934 and 2009","_format":"photographs","_name":"Bubley, Esther","_subjects":"Card catalogs; Priests; New York (N.Y.); Butler Library","_summary":"Image of a priest looking through card catalog."}, 
{"lunr_id":66,"link":"{{ site.baseurl }}/photos/69/","pid":"69","_title":"Business Library Reading Room","_date":"between 1934 and 2009","_format":"photographs","_name":"Warman, Manny, -1983","_subjects":"Academic libraries; Reading rooms; New York (N.Y.); Butler Library","_summary":"View of students in the Business Library reading room located in Butler Library."}, 
{"lunr_id":67,"link":"{{ site.baseurl }}/photos/7/","pid":"7","_title":"For Columbia Theater, A Festive First Night,' Article in the New York Times, September 17, 1988.","_date":"17-Sep-88","_format":"clippings","_name":"Kozinn, Allan; New York times","_subjects":"Theaters; Columbia University","_summary":"Photocopy of clipping from New York Times"}, 
{"lunr_id":68,"link":"{{ site.baseurl }}/photos/70/","pid":"70","_title":"Butler Library Construction 25","_date":"19-May-33","_format":"photographs","_name":"Beals, A. Tennyson","_subjects":"Academic libraries; New York (N.Y.); Butler Library","_summary":"Butler Library construction, 19 May 1933."}, 
{"lunr_id":69,"link":"{{ site.baseurl }}/photos/71/","pid":"71","_title":"Business Library Reading Room","_date":"circa 1934","_format":"photographs","_name":"Wurts Bros. (New York, N.Y.)","_subjects":"Academic libraries; Reading rooms; New York (N.Y.); Butler Library","_summary":"View of the Business Library Reading Room in South Hall (Butler Library), ca. 1934."}, 
{"lunr_id":70,"link":"{{ site.baseurl }}/photos/72/","pid":"72","_title":"Butler Library Construction 18","_date":"22-Dec-32","_format":"photographs","_name":"Beals, A. Tennyson","_subjects":"Academic libraries; New York (N.Y.); Butler Library","_summary":"Butler Library construction, 22 December 1932."}, 
{"lunr_id":71,"link":"{{ site.baseurl }}/photos/73/","pid":"73","_title":"Butler Library from Low Library Entrance","_date":"between 1934 and 2009","_format":"photographs","_name":"","_subjects":"Academic libraries; New York (N.Y.); Butler Library","_summary":"View of Butler Library as seen from the entrance of Low Memorial Library."}, 
{"lunr_id":72,"link":"{{ site.baseurl }}/photos/74/","pid":"74","_title":"Butler Library Construction 22","_date":"9-Mar-33","_format":"photographs","_name":"Beals, A. Tennyson","_subjects":"Academic libraries; New York (N.Y.); Butler Library","_summary":"Butler Library construction, 9 March 1933."}, 
{"lunr_id":73,"link":"{{ site.baseurl }}/photos/75/","pid":"75","_title":"Conservation Work Room","_date":"between 1934 and 2009","_format":"photographs","_name":"","_subjects":"Academic libraries; New York (N.Y.); Butler Library","_summary":"View of equipment in the Conservation work room."}, 
{"lunr_id":74,"link":"{{ site.baseurl }}/photos/76/","pid":"76","_title":"Book Transfer","_date":"between August 20 and September 19, 1934","_format":"photographs","_name":"Sprague","_subjects":"College campuses; New York (N.Y.)","_summary":"View of one portion of the book conveyor system from behind the Alma Mater statue on Low Plaza. Between August 20 and September 19, 1934 student workers and professional movers moved books from their original home in Low Library to their new home in South Hall (Butler Library)."}, 
{"lunr_id":75,"link":"{{ site.baseurl }}/photos/77/","pid":"77","_title":"Butler Library Construction 3","_date":"15-Jun-32","_format":"photographs","_name":"Beals, A. Tennyson","_subjects":"Academic libraries; New York (N.Y.); Butler Library","_summary":"Butler Library construction, 15 June 1932."}, 
{"lunr_id":76,"link":"{{ site.baseurl }}/photos/78/","pid":"78","_title":"Conservation Work Room","_date":"between 1934 and 2009","_format":"photographs","_name":"","_subjects":"Academic libraries; New York (N.Y.); Butler Library","_summary":"View of staff work spaces in the Conservation work room."}, 
{"lunr_id":77,"link":"{{ site.baseurl }}/photos/79/","pid":"79","_title":"Butler Library Construction 5","_date":"28-Jun-32","_format":"photographs","_name":"Beals, A. Tennyson","_subjects":"Academic libraries; New York (N.Y.); Butler Library","_summary":"Butler Library construction, 28 June 1932."}, 
{"lunr_id":78,"link":"{{ site.baseurl }}/photos/8/","pid":"8","_title":"Butler Library Office","_date":"between 1934 and 2009","_format":"photographs","_name":"","_subjects":"Academic libraries; New York (N.Y.); Butler Library","_summary":"View inside an office inside Butler Library on the third floor."}, 
{"lunr_id":79,"link":"{{ site.baseurl }}/photos/80/","pid":"80","_title":"Checking Sources","_date":"between 1934 and 2009","_format":"photographs","_name":"Warman, Manny, -1983","_subjects":"Academic libraries; College students; New York (N.Y.)","_summary":"'Theodore Shabad, assistant editor of the Gazetteer, checks data on source which include a Communist atlas published in 1950, and the China Postal Guide in both Chinese and English editions. '"}, 
{"lunr_id":80,"link":"{{ site.baseurl }}/photos/81/","pid":"81","_title":"Butler Library - Looking West","_date":"between 1934 and 2009","_format":"photographs","_name":"Warman, Manny, -1983","_subjects":"Academic libraries; New York (N.Y.); Butler Library","_summary":"View of Butler Library through foliage and a fence, looking west."}, 
{"lunr_id":81,"link":"{{ site.baseurl }}/photos/82/","pid":"82","_title":"Butler Library Construction 8","_date":"21-Jul-32","_format":"photographs","_name":"Beals, A. Tennyson","_subjects":"Academic libraries; New York (N.Y.); Butler Library","_summary":"Butler Library construction, 21 July 1932."}, 
{"lunr_id":82,"link":"{{ site.baseurl }}/photos/83/","pid":"83","_title":"Conservation Work Room","_date":"between 1934 and 2009","_format":"photographs","_name":"","_subjects":"Academic libraries; New York (N.Y.); Butler Library","_summary":"View of paper rolls in the Conservation department work room."}, 
{"lunr_id":83,"link":"{{ site.baseurl }}/photos/84/","pid":"84","_title":"Browsing Room","_date":"between 1934 and 2009","_format":"photographs","_name":"","_subjects":"Academic libraries; New York (N.Y.); Butler Library","_summary":"View of students in Butler Library's Browsing Room."}, 
{"lunr_id":84,"link":"{{ site.baseurl }}/photos/85/","pid":"85","_title":"Commencement 1953","_date":"1953","_format":"photographs","_name":"","_subjects":"Academic libraries; New York (N.Y.); Butler Library","_summary":"1953 Columbia graduate, holding two children, having his picture taken after the ceremony is over."}, 
{"lunr_id":85,"link":"{{ site.baseurl }}/photos/86/","pid":"86","_title":"Browsing Room","_date":"circa 1934","_format":"photographs","_name":"Wurts Bros. (New York, N.Y.)","_subjects":"Academic libraries; Reading rooms; New York (N.Y.); Butler Library","_summary":"View of South Hall (Butler Library) browsing room, ca. 1934."}, 
{"lunr_id":86,"link":"{{ site.baseurl }}/photos/87/","pid":"87","_title":"Binding Department","_date":"between 1934 and 2009","_format":"photographs","_name":"Ballou, Hubbard W.","_subjects":"Academic libraries; Bookbinding; New York (N.Y.); Butler Library","_summary":"Employees at work in the binding room with piles of books everywhere."}, 
{"lunr_id":87,"link":"{{ site.baseurl }}/photos/88/","pid":"88","_title":"Butler Library Construction 17","_date":"7-Dec-32","_format":"photographs","_name":"Beals, A. Tennyson","_subjects":"Academic libraries; New York (N.Y.); Butler Library","_summary":"Butler Library construction, 7 December 1932."}, 
{"lunr_id":88,"link":"{{ site.baseurl }}/photos/89/","pid":"89","_title":"Alcove in Browsing Room","_date":"circa 1934","_format":"photographs","_name":"Wurts Bros. (New York, N.Y.)","_subjects":"Academic libraries; Reading rooms; New York (N.Y.); Butler Library","_summary":"View of people sitting in an alcove in South Hall (Butler Library) browsing room, ca. 1934."}, 
{"lunr_id":89,"link":"{{ site.baseurl }}/photos/9/","pid":"9","_title":"General View of Columbia University","_date":"1898","_format":"photographs","_name":"Geo. P. Hall & Son","_subjects":"Columbia University; Low Memorial Library","_summary":""}, 
{"lunr_id":90,"link":"{{ site.baseurl }}/photos/90/","pid":"90","_title":"Butler Library Construction 24","_date":"5-Apr-33","_format":"photographs","_name":"Beals, A. Tennyson","_subjects":"Academic libraries; New York (N.Y.); Butler Library","_summary":"Butler Library construction, 5 April 1933."}, 
{"lunr_id":91,"link":"{{ site.baseurl }}/photos/91/","pid":"91","_title":"Butler Library from Avery","_date":"8-Sep-37","_format":"photographs","_name":"Bogert, W.L.","_subjects":"Academic libraries; New York (N.Y.); Butler Library","_summary":"View of Butler Library as seen from steps of Avery Library, 8 September 1937."}, 
{"lunr_id":92,"link":"{{ site.baseurl }}/photos/92/","pid":"92","_title":"Butler Library Construction 16","_date":"25-Nov-32","_format":"photographs","_name":"Beals, A. Tennyson","_subjects":"Academic libraries; New York (N.Y.); Butler Library","_summary":"Butler Library construction, 25 November 1932."}, 
{"lunr_id":93,"link":"{{ site.baseurl }}/photos/93/","pid":"93","_title":"Banned Books' Display","_date":"1954","_format":"photographs","_name":"Warman, Manny, -1983","_subjects":"Academic libraries; Prohibited books; New York (N.Y.)","_summary":"'Students pore over a display of 'Banned Books of All Ages' in Butler Library at Columbia University which is observing its 200th anniversary throughout 1954.'"}, 
{"lunr_id":94,"link":"{{ site.baseurl }}/photos/94/","pid":"94","_title":"College Study - Butler Library","_date":"between 1934 and 2009","_format":"photographs","_name":"","_subjects":"Academic libraries; New York (N.Y.); Butler Library","_summary":"View of students in the College Study located within Butler Library."}, 
{"lunr_id":95,"link":"{{ site.baseurl }}/photos/95/","pid":"95","_title":"Butler Library Construction 7","_date":"8-Jul-32","_format":"photographs","_name":"Beals, A. Tennyson","_subjects":"Academic libraries; New York (N.Y.); Butler Library","_summary":"Butler Library construction, 8 July 1932."}, 
{"lunr_id":96,"link":"{{ site.baseurl }}/photos/96/","pid":"96","_title":"Bonfire in Front of Butler Library","_date":"circa 1940-1949","_format":"photographs","_name":"Hopp, Morris J.","_subjects":"Academic libraries; Bonfires; New York (N.Y.); Butler Library","_summary":"Wide view of bonfire in front of Butler Library, ca. 1940s."}, 
{"lunr_id":97,"link":"{{ site.baseurl }}/photos/97/","pid":"97","_title":"Butler Library Construction 9","_date":"4-Aug-32","_format":"photographs","_name":"Beals, A. Tennyson","_subjects":"Academic libraries; New York (N.Y.); Butler Library","_summary":"Butler Library construction, 4 August 1932."}, 
{"lunr_id":98,"link":"{{ site.baseurl }}/photos/98/","pid":"98","_title":"Frosh-Soph Tug of War","_date":"between 1934 and 2009","_format":"photographs","_name":"","_subjects":"Academic libraries; New York (N.Y.); Butler Library","_summary":"Tug of war for Soph-Frosh Rush taking place in front of Butler Library."}, 
{"lunr_id":99,"link":"{{ site.baseurl }}/photos/99/","pid":"99","_title":"Butler Library Construction 15","_date":"22-Oct-32","_format":"photographs","_name":"Beals, A. Tennyson","_subjects":"Academic libraries; New York (N.Y.); Butler Library","_summary":"Butler Library construction, 22 October 1932."}];