language: ruby
rvm:
  - 2.4
script:
  - bundle exec jekyll build -d _site/historical-photos
  - bundle exec rake wax:test
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
