
title: Butler Library Historical Photo Collection
description: A CUL Jekiiil Demo from DLC Image Server
url: "http://mnyrop.github.io/butler-historical-photos"
permalink: pretty
markdown: kramdown
theme: minima

exclude: [ "Gemfile*" ]

collections:
    photos:
      source: historical-photos.yml
      output: true
      yml_split: true
      iiif: true
      layout: photo-page
      dir: photos
      manifest: true
      image: false
