
title: Butler Library Historical Photo Collection
description: A CUL Jekiiil Demo from DLC Image Server

url: ""
baseurl: "/historical-photos"
permalink: pretty
markdown: kramdown
theme: minima

exclude: [ "Gemfile*", "vendor", Rakefile, README.md ]

collections:
    photos:
      source: photos.csv
      layout: photo-page
      directory: photos

lunr:
  content: false
  meta:
    - dir: "photos"
      fields:
        - pid
        - title
        - _date
        - format
        - name
        - subjects
        - summary
